package com.cds.platform.trade;

import io.qameta.allure.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.*;
import org.springframework.test.context.ActiveProfiles;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Story 3.1 - CDS Trade Capture UI & Reference Data
 * Backend Integration Tests
 * 
 * Tests API endpoints for:
 * - Trade creation with validation
 * - Reference data retrieval
 * - Default value application
 * - Field validation rules
 * 
 * Generated by: Test Evidence Framework
 * Idempotent: Safe to regenerate
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
@Epic("Epic 03 - CDS Trade Capture")
@Feature("Trade API")
@DisplayName("Story 3.1 - CDS Trade Capture UI & Reference Data")
public class TradeStory3_1IntegrationTest {

    @Autowired
    private TestRestTemplate restTemplate;

    private HttpHeaders headers;

    @BeforeEach
    public void setUp() {
        headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
    }

    /**
     * AC1: API accepts all required CDS trade fields
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.CRITICAL)
    @Description("AC1: Verify API accepts complete trade with all Epic 3 fields")
    public void testAC1_createTradeWithAllFields() {
        // GIVEN - Complete trade request with all fields
        String requestBody = """
            {
              "tradeDate": "2025-01-15",
              "effectiveDate": "2025-01-15",
              "maturityDate": "2030-01-15",
              "accrualStartDate": "2025-01-15",
              "notionalAmount": 10000000.00,
              "spread": 150.0,
              "currency": "USD",
              "premiumFrequency": "QUARTERLY",
              "dayCountConvention": "ACT_360",
              "buySellProtection": "BUY",
              "paymentCalendar": "NYC",
              "restructuringClause": "",
              "tradeStatus": "PENDING"
            }
            """;

        // WHEN - POST to trade creation endpoint
        ResponseEntity<String> response = restTemplate.postForEntity(
            "/api/trades",
            new HttpEntity<>(requestBody, headers),
            String.class
        );

        // THEN - Trade created successfully
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        assertNotNull(response.getBody());
        assertTrue(response.getBody().contains("\"tradeId\""));
        assertTrue(response.getBody().contains("\"notionalAmount\":10000000"));
    }

    /**
     * AC2: API rejects trades missing required fields
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.CRITICAL)
    @Description("AC2: Verify API validates required fields and returns 400 for missing data")
    public void testAC2_rejectTradeWithMissingRequiredFields() {
        // GIVEN - Trade request missing notionalAmount (required field)
        String requestBody = """
            {
              "tradeDate": "2025-01-15",
              "effectiveDate": "2025-01-15",
              "maturityDate": "2030-01-15",
              "spread": 150.0,
              "currency": "USD"
            }
            """;

        // WHEN - POST to trade creation endpoint
        ResponseEntity<String> response = restTemplate.postForEntity(
            "/api/trades",
            new HttpEntity<>(requestBody, headers),
            String.class
        );

        // THEN - Request rejected with validation error
        assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
        assertNotNull(response.getBody());
        assertTrue(response.getBody().contains("notionalAmount") || 
                   response.getBody().contains("required"));
    }

    /**
     * AC3: API provides reference data for dropdowns
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.NORMAL)
    @Description("AC3: Verify reference data endpoints return currency, frequency, day count options")
    public void testAC3_getReferenceDataForDropdowns() {
        // WHEN - GET currency reference data
        ResponseEntity<String> currencyResponse = restTemplate.getForEntity(
            "/api/reference-data/currencies",
            String.class
        );

        // THEN - Currency options available
        assertEquals(HttpStatus.OK, currencyResponse.getStatusCode());
        assertNotNull(currencyResponse.getBody());
        assertTrue(currencyResponse.getBody().contains("USD"));
        assertTrue(currencyResponse.getBody().contains("EUR"));
        assertTrue(currencyResponse.getBody().contains("GBP"));
        assertTrue(currencyResponse.getBody().contains("JPY"));

        // WHEN - GET premium frequency reference data
        ResponseEntity<String> frequencyResponse = restTemplate.getForEntity(
            "/api/reference-data/premium-frequencies",
            String.class
        );

        // THEN - Frequency options available
        assertEquals(HttpStatus.OK, frequencyResponse.getStatusCode());
        assertTrue(frequencyResponse.getBody().contains("QUARTERLY"));
        assertTrue(frequencyResponse.getBody().contains("ANNUALLY"));
        assertTrue(frequencyResponse.getBody().contains("SEMI_ANNUALLY"));

        // WHEN - GET day count convention reference data
        ResponseEntity<String> dayCountResponse = restTemplate.getForEntity(
            "/api/reference-data/day-count-conventions",
            String.class
        );

        // THEN - Day count options available
        assertEquals(HttpStatus.OK, dayCountResponse.getStatusCode());
        assertTrue(dayCountResponse.getBody().contains("ACT_360"));
        assertTrue(dayCountResponse.getBody().contains("ACT_365"));
        assertTrue(dayCountResponse.getBody().contains("30_360"));
    }

    /**
     * AC4: API applies default values when not provided
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.NORMAL)
    @Description("AC4: Verify server applies defaults: currency=USD, frequency=QUARTERLY, etc.")
    public void testAC4_applyDefaultValues() {
        // GIVEN - Minimal trade request without optional defaults
        String requestBody = """
            {
              "tradeDate": "2025-01-15",
              "effectiveDate": "2025-01-15",
              "maturityDate": "2030-01-15",
              "notionalAmount": 5000000.00,
              "spread": 100.0
            }
            """;

        // WHEN - POST to trade creation endpoint
        ResponseEntity<String> response = restTemplate.postForEntity(
            "/api/trades",
            new HttpEntity<>(requestBody, headers),
            String.class
        );

        // THEN - Trade created with defaults applied
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        assertNotNull(response.getBody());
        
        // Verify defaults in response
        assertTrue(response.getBody().contains("\"currency\":\"USD\""));
        assertTrue(response.getBody().contains("\"premiumFrequency\":\"QUARTERLY\""));
        assertTrue(response.getBody().contains("\"dayCountConvention\":\"ACT_360\""));
        assertTrue(response.getBody().contains("\"buySellProtection\":\"BUY\""));
        assertTrue(response.getBody().contains("\"paymentCalendar\":\"NYC\""));
        assertTrue(response.getBody().contains("\"tradeStatus\":\"PENDING\""));
    }

    /**
     * AC5: API accepts trades with empty restructuring clause
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.NORMAL)
    @Description("AC5: Verify optional field (restructuringClause) can be blank/null")
    public void testAC5_allowEmptyRestructuringClause() {
        // GIVEN - Trade request with empty restructuring clause
        String requestBody = """
            {
              "tradeDate": "2025-01-15",
              "effectiveDate": "2025-01-15",
              "maturityDate": "2030-01-15",
              "notionalAmount": 8000000.00,
              "spread": 120.0,
              "currency": "EUR",
              "restructuringClause": null
            }
            """;

        // WHEN - POST to trade creation endpoint
        ResponseEntity<String> response = restTemplate.postForEntity(
            "/api/trades",
            new HttpEntity<>(requestBody, headers),
            String.class
        );

        // THEN - Trade created successfully (no validation error)
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        assertNotNull(response.getBody());
        assertTrue(response.getBody().contains("\"tradeId\""));
    }

    /**
     * AC6 - Validation Rule 1: Notional Amount > 0
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.CRITICAL)
    @Description("AC6: Validate notionalAmount > 0")
    public void testAC6_validateNotionalAmountGreaterThanZero() {
        // GIVEN - Trade with zero notional amount
        String requestBody = """
            {
              "tradeDate": "2025-01-15",
              "effectiveDate": "2025-01-15",
              "maturityDate": "2030-01-15",
              "notionalAmount": 0.00,
              "spread": 150.0,
              "currency": "USD"
            }
            """;

        // WHEN - POST to trade creation endpoint
        ResponseEntity<String> response = restTemplate.postForEntity(
            "/api/trades",
            new HttpEntity<>(requestBody, headers),
            String.class
        );

        // THEN - Request rejected with validation error
        assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
        assertTrue(response.getBody().contains("notionalAmount") || 
                   response.getBody().contains("greater than 0"));
    }

    /**
     * AC6 - Validation Rule 2: Spread >= 0
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.CRITICAL)
    @Description("AC6: Validate spread >= 0")
    public void testAC6_validateSpreadNonNegative() {
        // GIVEN - Trade with negative spread
        String requestBody = """
            {
              "tradeDate": "2025-01-15",
              "effectiveDate": "2025-01-15",
              "maturityDate": "2030-01-15",
              "notionalAmount": 10000000.00,
              "spread": -50.0,
              "currency": "USD"
            }
            """;

        // WHEN - POST to trade creation endpoint
        ResponseEntity<String> response = restTemplate.postForEntity(
            "/api/trades",
            new HttpEntity<>(requestBody, headers),
            String.class
        );

        // THEN - Request rejected with validation error
        assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
        assertTrue(response.getBody().contains("spread") || 
                   response.getBody().contains("non-negative") ||
                   response.getBody().contains("greater than or equal to 0"));
    }

    /**
     * AC6 - Validation Rule 3: Effective Date >= Trade Date
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.CRITICAL)
    @Description("AC6: Validate effectiveDate >= tradeDate")
    public void testAC6_validateEffectiveDateNotBeforeTradeDate() {
        // GIVEN - Trade with effective date before trade date
        String requestBody = """
            {
              "tradeDate": "2025-01-15",
              "effectiveDate": "2025-01-10",
              "maturityDate": "2030-01-15",
              "notionalAmount": 10000000.00,
              "spread": 150.0,
              "currency": "USD"
            }
            """;

        // WHEN - POST to trade creation endpoint
        ResponseEntity<String> response = restTemplate.postForEntity(
            "/api/trades",
            new HttpEntity<>(requestBody, headers),
            String.class
        );

        // THEN - Request rejected with validation error
        assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
        assertTrue(response.getBody().contains("effectiveDate") || 
                   response.getBody().contains("tradeDate") ||
                   response.getBody().contains("on or after"));
    }

    /**
     * AC6 - Validation Rule 4: Maturity Date > Effective Date
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.CRITICAL)
    @Description("AC6: Validate maturityDate > effectiveDate")
    public void testAC6_validateMaturityDateAfterEffectiveDate() {
        // GIVEN - Trade with maturity date before effective date
        String requestBody = """
            {
              "tradeDate": "2025-01-15",
              "effectiveDate": "2025-01-15",
              "maturityDate": "2025-01-10",
              "notionalAmount": 10000000.00,
              "spread": 150.0,
              "currency": "USD"
            }
            """;

        // WHEN - POST to trade creation endpoint
        ResponseEntity<String> response = restTemplate.postForEntity(
            "/api/trades",
            new HttpEntity<>(requestBody, headers),
            String.class
        );

        // THEN - Request rejected with validation error
        assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
        assertTrue(response.getBody().contains("maturityDate") || 
                   response.getBody().contains("effectiveDate") ||
                   response.getBody().contains("after"));
    }

    /**
     * AC6 - Validation Rule 5: Accrual Start Date <= Effective Date
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.CRITICAL)
    @Description("AC6: Validate accrualStartDate <= effectiveDate")
    public void testAC6_validateAccrualStartDateNotAfterEffectiveDate() {
        // GIVEN - Trade with accrual start date after effective date
        String requestBody = """
            {
              "tradeDate": "2025-01-15",
              "effectiveDate": "2025-01-15",
              "maturityDate": "2030-01-15",
              "accrualStartDate": "2025-01-20",
              "notionalAmount": 10000000.00,
              "spread": 150.0,
              "currency": "USD"
            }
            """;

        // WHEN - POST to trade creation endpoint
        ResponseEntity<String> response = restTemplate.postForEntity(
            "/api/trades",
            new HttpEntity<>(requestBody, headers),
            String.class
        );

        // THEN - Request rejected with validation error
        assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
        assertTrue(response.getBody().contains("accrualStartDate") || 
                   response.getBody().contains("effectiveDate") ||
                   response.getBody().contains("on or before"));
    }

    /**
     * Integration Test: Complete trade lifecycle
     */
    @Test
    @Story("Story 3.1 - CDS Trade Capture UI & Reference Data")
    @Severity(SeverityLevel.BLOCKER)
    @Description("End-to-end: Create trade, retrieve it, verify all fields persisted")
    public void testIntegration_completeTradeLifecycle() {
        // GIVEN - Valid trade request
        String createRequestBody = """
            {
              "tradeDate": "2025-01-15",
              "effectiveDate": "2025-01-15",
              "maturityDate": "2030-01-15",
              "accrualStartDate": "2025-01-15",
              "notionalAmount": 15000000.00,
              "spread": 175.0,
              "currency": "GBP",
              "premiumFrequency": "SEMI_ANNUALLY",
              "dayCountConvention": "ACT_365",
              "buySellProtection": "SELL",
              "paymentCalendar": "LON",
              "restructuringClause": "CR"
            }
            """;

        // WHEN - Create trade
        ResponseEntity<String> createResponse = restTemplate.postForEntity(
            "/api/trades",
            new HttpEntity<>(createRequestBody, headers),
            String.class
        );

        // THEN - Trade created successfully
        assertEquals(HttpStatus.CREATED, createResponse.getStatusCode());
        assertNotNull(createResponse.getBody());
        assertTrue(createResponse.getBody().contains("\"tradeId\""));

        // Extract tradeId from response
        String tradeId = createResponse.getBody().split("\"tradeId\":\"")[1].split("\"")[0];

        // WHEN - Retrieve created trade
        ResponseEntity<String> getResponse = restTemplate.getForEntity(
            "/api/trades/" + tradeId,
            String.class
        );

        // THEN - Trade retrieved with all fields intact
        assertEquals(HttpStatus.OK, getResponse.getStatusCode());
        String retrievedTrade = getResponse.getBody();
        
        assertTrue(retrievedTrade.contains("\"notionalAmount\":15000000"));
        assertTrue(retrievedTrade.contains("\"spread\":175"));
        assertTrue(retrievedTrade.contains("\"currency\":\"GBP\""));
        assertTrue(retrievedTrade.contains("\"premiumFrequency\":\"SEMI_ANNUALLY\""));
        assertTrue(retrievedTrade.contains("\"dayCountConvention\":\"ACT_365\""));
        assertTrue(retrievedTrade.contains("\"buySellProtection\":\"SELL\""));
        assertTrue(retrievedTrade.contains("\"paymentCalendar\":\"LON\""));
        assertTrue(retrievedTrade.contains("\"restructuringClause\":\"CR\""));
    }
}
