version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cdsplatform
      POSTGRES_USER: cdsuser
      POSTGRES_PASSWORD: cdspass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cdsuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cdsplatform
      SPRING_DATASOURCE_USERNAME: cdsuser
      SPRING_DATASOURCE_PASSWORD: cdspass
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    build:
      context: ./gateway
    ports:
      - "8081:8081"
    depends_on:
      backend:
        condition: service_healthy
      risk-engine:
        condition: service_started
    environment:
      SERVER_PORT: 8081
      BACKEND_URI: http://backend:8080
      RISK_ENGINE_URI: http://risk-engine:8082

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8081/api
      NODE_ENV: development
    depends_on:
      - gateway

  risk-engine:
    build:
      context: ./risk-engine
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      RISK_IMPL: ORE
      ORE_BINARY_PATH: /app/ore/bin/ore
      ORE_CONFIG_PATH: /app/ore/config/ore_cds.xml
      # Use host.docker.internal to reach services on host machine
      BACKEND_BASE_URL: http://host.docker.internal:8080
    volumes:
      # Mount your local ORE binary and config
      - ./ore-setup/bin:/app/ore/bin:ro
      - ./ore-setup/config:/app/ore/config:ro
      - ./ore-setup/market-data:/app/ore/market-data:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    # Enable host networking for macOS/Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: