server:
  port: 8082

spring:
  application:
    name: risk-engine

# Risk Engine Configuration - ORE Only
risk:
  ore:
    binary-path: ${ORE_BINARY_PATH:/app/ore/bin/ore}
    config-path: ${ORE_CONFIG_PATH:/app/ore/config/ore.xml}
    work-dir: ${ORE_WORK_DIR:/tmp/ore-work}
    timeout-seconds: ${ORE_TIMEOUT:10}
    warmup-timeout-seconds: ${ORE_WARMUP_TIMEOUT:30}
    restart-delay-seconds: ${ORE_RESTART_DELAY:5}
    max-restarts: ${ORE_MAX_RESTARTS:3}
    debug: ${ORE_DEBUG:false}

# Backend service connection
backend:
  base:
    url: ${BACKEND_BASE_URL:http://localhost:8080}

logging:
  level:
    com.creditdefaultswap.riskengine: INFO
    com.creditdefaultswap.riskengine.ore: DEBUG
    com.creditdefaultswap.riskengine.controller: INFO
    org.springframework.web: WARN
    org.springframework.web.servlet.DispatcherServlet: WARN
    org.apache.catalina: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always