server:
  port: 8082

spring:
  application:
    name: risk-engine

logging:
  level:
    com.creditdefaultswap.riskengine: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always