services:
  - type: web
    name: defectdojo
    env: docker
    plan: standard
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health-check.sh
    autoDeploy: false
    envVars:
      - key: DD_SECRET_KEY
        generateValue: true
      - key: DD_CREDENTIAL_AES_256_KEY
        generateValue: true
      - key: DD_ALLOWED_HOSTS
        value: "*"
      - key: DD_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DD_DEBUG
        value: "False"
      - key: DD_ADMIN_USER
        value: "admin"
      - key: DD_ADMIN_PASSWORD
        sync: false
      - key: DD_ADMIN_MAIL
        value: "admin@defectdojo.local"
      - key: DD_SESSION_COOKIE_SECURE
        value: "True"
      - key: DD_CSRF_COOKIE_SECURE
        value: "True"
      - key: DD_SESSION_COOKIE_HTTPONLY
        value: "True"
      - key: DD_CSRF_COOKIE_HTTPONLY
        value: "False"
      - key: DD_SESSION_COOKIE_SAMESITE
        value: "Lax"
      - key: DD_CSRF_COOKIE_SAMESITE
        value: "Lax"
      - key: DD_INITIALIZE
        value: "true"
      - key: PORT
        value: "10000"
      - key: DB_PASSWORD
        generateValue: true
    disk:
      name: defectdojo-data
      mountPath: /app/pgdata
      sizeGB: 10