spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # Aggressively recreate schema in dev mode
    show-sql: true
  flyway:
    enabled: false  # Temporarily disable Flyway to bypass migration conflicts
    clean-on-validation-error: true
